In [198]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [199]:
df=pd.read_csv("anime.csv")

In [200]:
df1=pd.read_csv("anime_with_synopsis.csv")

In [201]:
df.head(2)

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,...,Score-10,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",Cowboy Bebop,カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,...,229170.0,182126.0,131625.0,62330.0,20688.0,8904.0,3184.0,1357.0,741.0,1580.0
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Cowboy Bebop:The Movie,カウボーイビバップ 天国の扉,Movie,1,"Sep 1, 2001",Unknown,...,30043.0,49201.0,49505.0,22632.0,5805.0,1877.0,577.0,221.0,109.0,379.0

In [202]:
df1.head(5)

,MAL_ID,Name,Score,Genres,sypnopsis
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space","In the year 2071, humanity has colonized sever..."
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space","other day, another bounty—such is the life of ..."
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen","Vash the Stampede is the man with a $$60,000,0..."
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",ches are individuals with special powers like ...
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",It is the dark century and the people are suff...

In [203]:
df1.drop("Name",axis=1,inplace=True)
df1.drop("Score",axis=1,inplace=True)
df1.drop("Genres",axis=1,inplace=True)

In [204]:
df.columns

Index(['MAL_ID', 'Name', 'Score', 'Genres', 'English name', 'Japanese name',
       'Type', 'Episodes', 'Aired', 'Premiered', 'Producers', 'Licensors',
       'Studios', 'Source', 'Duration', 'Rating', 'Ranked', 'Popularity',
       'Members', 'Favorites', 'Watching', 'Completed', 'On-Hold', 'Dropped',
       'Plan to Watch', 'Score-10', 'Score-9', 'Score-8', 'Score-7', 'Score-6',
       'Score-5', 'Score-4', 'Score-3', 'Score-2', 'Score-1'],
      dtype='object')

In [205]:
df.drop("English name",axis=1,inplace=True)
df.drop("Producers",axis=1,inplace=True)
df.drop("Licensors",axis=1,inplace=True)
df.drop("Source",axis=1,inplace=True)
df.drop("Members",axis=1,inplace=True)
df.drop("Favorites",axis=1,inplace=True)
df.drop("Watching",axis=1,inplace=True)
df.drop("Completed",axis=1,inplace=True)
df.drop(["On-Hold", 'Dropped','Plan to Watch', 'Score-10', 'Score-9', 'Score-8', 'Score-7', 'Score-6','Score-5', 'Score-4', 'Score-3', 'Score-2', 'Score-1'],axis=1,inplace=True)

In [206]:
df.head(3)

,MAL_ID,Name,Score,Genres,Japanese name,Type,Episodes,Aired,Premiered,Studios,Duration,Rating,Ranked,Popularity
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,Sunrise,24 min. per ep.,R - 17+ (violence & profanity),28.0,39
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",カウボーイビバップ 天国の扉,Movie,1,"Sep 1, 2001",Unknown,Bones,1 hr. 55 min.,R - 17+ (violence & profanity),159.0,518
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",トライガン,TV,26,"Apr 1, 1998 to Sep 30, 1998",Spring 1998,Madhouse,24 min. per ep.,PG-13 - Teens 13 or older,266.0,201

In [207]:
df.columns

Index(['MAL_ID', 'Name', 'Score', 'Genres', 'Japanese name', 'Type',
       'Episodes', 'Aired', 'Premiered', 'Studios', 'Duration', 'Rating',
       'Ranked', 'Popularity'],
      dtype='object')

In [208]:
df2=df1.merge(df,on='MAL_ID')

In [209]:
df2.head(4)

,MAL_ID,sypnopsis,Name,Score,Genres,Japanese name,Type,Episodes,Aired,Premiered,Studios,Duration,Rating,Ranked,Popularity
0,1,"In the year 2071, humanity has colonized sever...",Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,Sunrise,24 min. per ep.,R - 17+ (violence & profanity),28.0,39
1,5,"other day, another bounty—such is the life of ...",Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",カウボーイビバップ 天国の扉,Movie,1,"Sep 1, 2001",Unknown,Bones,1 hr. 55 min.,R - 17+ (violence & profanity),159.0,518
2,6,"Vash the Stampede is the man with a $$60,000,0...",Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",トライガン,TV,26,"Apr 1, 1998 to Sep 30, 1998",Spring 1998,Madhouse,24 min. per ep.,PG-13 - Teens 13 or older,266.0,201
3,7,ches are individuals with special powers like ...,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",Witch Hunter ROBIN (ウイッチハンターロビン),TV,26,"Jul 2, 2002 to Dec 24, 2002",Summer 2002,Sunrise,25 min. per ep.,PG-13 - Teens 13 or older,2481.0,1467

In [210]:
df2.columns

Index(['MAL_ID', 'sypnopsis', 'Name', 'Score', 'Genres', 'Japanese name',
       'Type', 'Episodes', 'Aired', 'Premiered', 'Studios', 'Duration',
       'Rating', 'Ranked', 'Popularity'],
      dtype='object')

In [211]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16214 entries, 0 to 16213
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MAL_ID         16214 non-null  int64
 1   sypnopsis      16206 non-null  object
 2   Name           16214 non-null  object
 3   Score          16214 non-null  object
 4   Genres         16214 non-null  object
 5   Japanese name  16214 non-null  object
 6   Type           16214 non-null  object
 7   Episodes       16214 non-null  object
 8   Aired          16214 non-null  object
 9   Premiered      16214 non-null  object
 10  Studios        16214 non-null  object
 11  Duration       16214 non-null  object
 12  Rating         16214 non-null  object
 13  Ranked         16214 non-null  object
 14  Popularity     16214 non-null  int64
dtypes: int64(2), object(13)
memory usage: 2.0+ MB

In [212]:
df2['Popularity']=df2['Popularity'].astype(str)

In [213]:
df2.drop_duplicates(subset ="Name", keep = 'last', inplace = True)

In [214]:
df2.iloc[0].Genres

'Action, Adventure, Comedy, Drama, Sci-Fi, Space'

In [215]:
df2.dropna(inplace=True)

In [216]:
df2.head()

,MAL_ID,sypnopsis,Name,Score,Genres,Japanese name,Type,Episodes,Aired,Premiered,Studios,Duration,Rating,Ranked,Popularity
0,1,"In the year 2071, humanity has colonized sever...",Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,Sunrise,24 min. per ep.,R - 17+ (violence & profanity),28.0,39
1,5,"other day, another bounty—such is the life of ...",Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",カウボーイビバップ 天国の扉,Movie,1,"Sep 1, 2001",Unknown,Bones,1 hr. 55 min.,R - 17+ (violence & profanity),159.0,518
2,6,"Vash the Stampede is the man with a $$60,000,0...",Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",トライガン,TV,26,"Apr 1, 1998 to Sep 30, 1998",Spring 1998,Madhouse,24 min. per ep.,PG-13 - Teens 13 or older,266.0,201
3,7,ches are individuals with special powers like ...,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",Witch Hunter ROBIN (ウイッチハンターロビン),TV,26,"Jul 2, 2002 to Dec 24, 2002",Summer 2002,Sunrise,25 min. per ep.,PG-13 - Teens 13 or older,2481.0,1467
4,8,It is the dark century and the people are suff...,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",冒険王ビィト,TV,52,"Sep 30, 2004 to Sep 29, 2005",Fall 2004,Toei Animation,23 min. per ep.,PG - Children,3710.0,4369

In [217]:
df2.duplicated().sum()

0

In [ ]:
df2['sypnopsis'] = df2['sypnopsis'].apply(lambda x:x.split())

In [223]:
df2.head()

,MAL_ID,sypnopsis,Name,Score,Genres,Japanese name,Type,Episodes,Aired,Premiered,Studios,Duration,Rating,Ranked,Popularity
0,1,"[In, the, year, 2071,, humanity, has, colonize...",Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,Sunrise,24 min. per ep.,R - 17+ (violence & profanity),28.0,39
1,5,"[other, day,, another, bounty—such, is, the, l...",Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",カウボーイビバップ 天国の扉,Movie,1,"Sep 1, 2001",Unknown,Bones,1 hr. 55 min.,R - 17+ (violence & profanity),159.0,518
2,6,"[Vash, the, Stampede, is, the, man, with, a, $...",Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",トライガン,TV,26,"Apr 1, 1998 to Sep 30, 1998",Spring 1998,Madhouse,24 min. per ep.,PG-13 - Teens 13 or older,266.0,201
3,7,"[ches, are, individuals, with, special, powers...",Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",Witch Hunter ROBIN (ウイッチハンターロビン),TV,26,"Jul 2, 2002 to Dec 24, 2002",Summer 2002,Sunrise,25 min. per ep.,PG-13 - Teens 13 or older,2481.0,1467
4,8,"[It, is, the, dark, century, and, the, people,...",Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",冒険王ビィト,TV,52,"Sep 30, 2004 to Sep 29, 2005",Fall 2004,Toei Animation,23 min. per ep.,PG - Children,3710.0,4369

In [224]:
df2['Genres']=df2['Genres'].apply(lambda x:x.split())

In [226]:
df2['Studios']=df2['Studios'].apply(lambda x:x.split())

In [227]:
df2.head()

,MAL_ID,sypnopsis,Name,Score,Genres,Japanese name,Type,Episodes,Aired,Premiered,Studios,Duration,Rating,Ranked,Popularity
0,1,"[In, the, year, 2071,, humanity, has, colonize...",Cowboy Bebop,8.78,"[Action,, Adventure,, Comedy,, Drama,, Sci-Fi,...",カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,[Sunrise],24 min. per ep.,R - 17+ (violence & profanity),28.0,39
1,5,"[other, day,, another, bounty—such, is, the, l...",Cowboy Bebop: Tengoku no Tobira,8.39,"[Action,, Drama,, Mystery,, Sci-Fi,, Space]",カウボーイビバップ 天国の扉,Movie,1,"Sep 1, 2001",Unknown,[Bones],1 hr. 55 min.,R - 17+ (violence & profanity),159.0,518
2,6,"[Vash, the, Stampede, is, the, man, with, a, $...",Trigun,8.24,"[Action,, Sci-Fi,, Adventure,, Comedy,, Drama,...",トライガン,TV,26,"Apr 1, 1998 to Sep 30, 1998",Spring 1998,[Madhouse],24 min. per ep.,PG-13 - Teens 13 or older,266.0,201
3,7,"[ches, are, individuals, with, special, powers...",Witch Hunter Robin,7.27,"[Action,, Mystery,, Police,, Supernatural,, Dr...",Witch Hunter ROBIN (ウイッチハンターロビン),TV,26,"Jul 2, 2002 to Dec 24, 2002",Summer 2002,[Sunrise],25 min. per ep.,PG-13 - Teens 13 or older,2481.0,1467
4,8,"[It, is, the, dark, century, and, the, people,...",Bouken Ou Beet,6.98,"[Adventure,, Fantasy,, Shounen,, Supernatural]",冒険王ビィト,TV,52,"Sep 30, 2004 to Sep 29, 2005",Fall 2004,"[Toei, Animation]",23 min. per ep.,PG - Children,3710.0,4369

In [228]:
df2['Type']=df2['Type'].apply(lambda x:x.split())

In [229]:
df2['tags']=df2['sypnopsis']+df2['Genres']+df2['Studios']+df2['Type']

In [231]:
new = df2.drop(columns=['sypnopsis','Genres','Studios','Type'])

In [232]:
new['tags'] = new['tags'].apply(lambda x: " ".join(x))
new.head()

,MAL_ID,Name,Score,Japanese name,Episodes,Aired,Premiered,Duration,Rating,Ranked,Popularity,tags
0,1,Cowboy Bebop,8.78,カウボーイビバップ,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,24 min. per ep.,R - 17+ (violence & profanity),28.0,39,"In the year 2071, humanity has colonized sever..."
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,カウボーイビバップ 天国の扉,1,"Sep 1, 2001",Unknown,1 hr. 55 min.,R - 17+ (violence & profanity),159.0,518,"other day, another bounty—such is the life of ..."
2,6,Trigun,8.24,トライガン,26,"Apr 1, 1998 to Sep 30, 1998",Spring 1998,24 min. per ep.,PG-13 - Teens 13 or older,266.0,201,"Vash the Stampede is the man with a $$60,000,0..."
3,7,Witch Hunter Robin,7.27,Witch Hunter ROBIN (ウイッチハンターロビン),26,"Jul 2, 2002 to Dec 24, 2002",Summer 2002,25 min. per ep.,PG-13 - Teens 13 or older,2481.0,1467,ches are individuals with special powers like ...
4,8,Bouken Ou Beet,6.98,冒険王ビィト,52,"Sep 30, 2004 to Sep 29, 2005",Fall 2004,23 min. per ep.,PG - Children,3710.0,4369,It is the dark century and the people are suff...

In [233]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [234]:

vector = cv.fit_transform(new['tags']).toarray()

In [235]:

vector.shape

(16202, 5000)

In [236]:
from sklearn.metrics.pairwise import cosine_similarity

In [237]:
similarity = cosine_similarity(vector)

In [238]:
similarity

array([[1.        , 0.25813436, 0.14294834, ..., 0.03094922, 0.17868542,
        0.1925571 ],
       [0.25813436, 1.        , 0.14713826, ..., 0.0347524 , 0.04012862,
        0.08648775],
       [0.14294834, 0.14713826, 1.        , ..., 0.03207501, 0.18518519,
        0.03991229],
       ...,
       [0.03094922, 0.0347524 , 0.03207501, ..., 1.        , 0.09622504,
        0.05184758],
       [0.17868542, 0.04012862, 0.18518519, ..., 0.09622504, 1.        ,
        0.11973687],
       [0.1925571 , 0.08648775, 0.03991229, ..., 0.05184758, 0.11973687,
        1.        ]])

In [240]:
new[new['Name'] == 'Cowboy Bebop: Tengoku no Tobira'].index[0]

1

In [245]:

def recommend(movie):
    index = new[new['Name'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new.iloc[i[0]].Name)

In [255]:
recommend('One Piece')

One Piece: Episode of East Blue - Luffy to 4-nin no Nakama no Daibouken
One Piece: Romance Dawn Story
One Piece Film: Strong World
One Piece Film: Strong World Episode 0
One Piece Film: Z

In [256]:
import pickle

In [257]:

pickle.dump(new,open('anime_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))